### ISSUE TITLE
Demo version vs latest stable version

### ISSUE THREAD

**Issue by Gman1988** [Net-ng/kansha#250]
Hi i just tested demo version and its fantastic.

But when i used docker image with version  1.0.6 i see that template options is missing.

How can i use the same version that on the demo on the stie ?

**Comment by Net-ng** [comment]
Hello!

Thank you for your feedback. We're glad you like Kansha.

The demo version is a development snapshot. Even more work has been 
done since then and we are currently preparing a new stable release.

If you are impatient, you can start off the master branch by following 
the instructions here: 
http://kansha.readthedocs.io/en/latest/quickstart.html#python-package

Tell us if you have any difficulty.


Romuald Texier-Marcadé
02 23 21 21 50
Ingénieur de développement

Net-ng
6, rue de Jouanet
35700 RENNES
http://www.net-ng.com/

**Comment by Gman1988** [comment]
Thanks for answear i have two more questions:

- when you plan to release next stable version ?
- how to start off the master branch version ? i used those instructions but instruction
easy_install --find-links=http://www.nagare.org/snapshots/  kansha==1.1.0

dont work ;/

**Comment by rtxm** [comment]
Sorry, my bad! The actual instructions you need to start off the master branch are there: http://kansha.readthedocs.io/en/latest/devsetup.html

The master branch needs to undergo extensive testing before we make an official stable release. There is no due date yet.

Stay tunned and update your local copy of the master branch to get the latest fixes.

**Comment by Gman1988** [comment]
Ok i tried to manage this and its working, but i want to make this easy and fast to deploy and this is not the best solution.

When you release the newest version with docker ?

**Comment by rtxm** [comment]
Stable releases are automatically pushed to pypi and docker hub. The (much awaited) next stable release in near, but I can't give any schedule yet.

**Comment by rtxm** [comment]
Hello!
Kansha v2.0.0 has just been released! Follow the instruction on the README to try it in docker.
